### ISSUE TITLE
phone number data types not being parsed correctly

### ISSUE THREAD

**Issue by clhenrick** [IWSLLC/json-csv#13] opened 2015-04-08 03:23 UTC
Trying to convert json data containing phone number data such as "(888) 888-8888" results in empty values in the CSV output. 

Sample code and data available [here](https://gist.github.com/clhenrick/4a9db08f6cd8995024f5).

**Comment by nathanb** [comment] 2015-11-11 20:17
Wow, I totally missed this by seven months. Apologies!  I did create a test for it that shows the fail. The problem is, in order to support the dot-notation for nested JSON objects, I can't support objects with key values containing periods (at least not easily). 

We can probably get clever and do something like, "The key ends with a period so it must be part of the key and not a dot-notation into a sub-objects".  But that's a little messy.  Honestly, it would be best if you ran that JSON data through a filter first and tweaked its field name from `phone no.` to `phone no` and then piped that into the exporter. 

Again, apologies for the delay. I'm going to close this one can call it a "known issue".

**Closed by nathanb** 2015-11-11 20:17 UTC

**Comment by clhenrick** [comment] 2015-11-11 20:20
Thanks and no worries! Apologies for missing the test.
